name: Check PRs on Sports service

on:
  pull_request:
    branches: [ "develop", "main" ]
    paths:
      - "projects/sports/**"
    types: [ opened, synchronize, reopened ]

jobs:
  lint-tests-coverage:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry && poetry config virtualenvs.create false
          poetry install
          cd projects/sports && poetry install

      - name: Run lint
        run: |
          poetry run pre-commit run --all-files

      - name: Run unit tests and coverage
        run: |
          cd projects/sports
          poetry run coverage run -m pytest tests/unit
          poetry run coverage report -m --fail-under=75
          poetry run coverage xml

      - name: fix code coverage paths
        run: |
          sed -i 's/\/home\/runner\/work\/sportapp-back\/sportapp-back\//\/github\/workspace\//g' projects/sports/coverage.xml

      - name: Run integration tests
        run: |
          cd projects/sports
          poetry run pytest tests/integration

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        with:
          projectBaseDir: projects/sports
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
